<?php

namespace Database\Seeders;

use App\Models\Place;
use Illuminate\Database\Seeder;

class PlaceSeeder extends Seeder
{
    public function run(): void
    {
        $places = [
            // 제주도
            [
                'name'          => '성산일출봉',
                'description'   => '유네스코 세계자연유산으로 지정된 제주의 대표 명소. 수성화산의 웅장한 분화구와 일출 풍경이 유명하다.',
                'address'       => '제주특별자치도 서귀포시 성산읍 일출로 284-12',
                'city'          => '서귀포',
                'country'       => '한국',
                'latitude'      => 33.4589,
                'longitude'     => 126.9425,
                'category'      => 'attraction',
                'thumbnail_url' => null,
                'rating'        => 4.8,
            ],
            [
                'name'          => '한라산 국립공원',
                'description'   => '대한민국 최고봉(1,950m). 유네스코 세계자연유산이자 생물권보전지역으로 다양한 등산 코스를 제공한다.',
                'address'       => '제주특별자치도 제주시 516로 2070',
                'city'          => '제주',
                'country'       => '한국',
                'latitude'      => 33.3617,
                'longitude'     => 126.5292,
                'category'      => 'attraction',
                'thumbnail_url' => null,
                'rating'        => 4.9,
            ],
            [
                'name'          => '만장굴',
                'description'   => '총 길이 7.4km의 세계 최대급 용암동굴. 천연기념물 제98호로 신비로운 지하 세계를 탐험할 수 있다.',
                'address'       => '제주특별자치도 제주시 구좌읍 만장굴길 182',
                'city'          => '제주',
                'country'       => '한국',
                'latitude'      => 33.5283,
                'longitude'     => 126.7714,
                'category'      => 'attraction',
                'thumbnail_url' => null,
                'rating'        => 4.6,
            ],
            [
                'name'          => '섭지코지',
                'description'   => '성산읍 해안에 위치한 아름다운 돌출 지형. 드라마 올인 촬영지로 유명하며 등대와 유채꽃밭이 인상적이다.',
                'address'       => '제주특별자치도 서귀포시 성산읍 고성리 224-33',
                'city'          => '서귀포',
                'country'       => '한국',
                'latitude'      => 33.4283,
                'longitude'     => 126.9308,
                'category'      => 'attraction',
                'thumbnail_url' => null,
                'rating'        => 4.5,
            ],
            [
                'name'          => '협재해수욕장',
                'description'   => '에메랄드빛 바다와 하얀 모래사장이 어우러진 제주 서쪽 대표 해변. 비양도 전망이 아름답다.',
                'address'       => '제주특별자치도 제주시 한림읍 협재리 2497-1',
                'city'          => '제주',
                'country'       => '한국',
                'latitude'      => 33.3941,
                'longitude'     => 126.2394,
                'category'      => 'beach',
                'thumbnail_url' => null,
                'rating'        => 4.7,
            ],
            [
                'name'          => '우도',
                'description'   => '제주 동쪽 끝에 위치한 작은 섬. 우도봉, 홍조단괴 해빈, 땅콩 아이스크림으로 유명하다.',
                'address'       => '제주특별자치도 제주시 우도면 우도해안길',
                'city'          => '제주',
                'country'       => '한국',
                'latitude'      => 33.5015,
                'longitude'     => 126.9551,
                'category'      => 'attraction',
                'thumbnail_url' => null,
                'rating'        => 4.7,
            ],
            [
                'name'          => '흑돼지거리',
                'description'   => '제주 흑돼지 구이를 전문으로 하는 음식점들이 밀집한 거리. 제주시 연동에 위치하며 현지인과 관광객 모두에게 인기.',
                'address'       => '제주특별자치도 제주시 연동 흑돼지거리',
                'city'          => '제주',
                'country'       => '한국',
                'latitude'      => 33.4996,
                'longitude'     => 126.5312,
                'category'      => 'restaurant',
                'thumbnail_url' => null,
                'rating'        => 4.5,
            ],
            // 부산
            [
                'name'          => '해운대해수욕장',
                'description'   => '국내 최대 규모의 해수욕장. 여름 피서지로 유명하며 마린시티와 달맞이고개가 인근에 있다.',
                'address'       => '부산광역시 해운대구 해운대해변로 264',
                'city'          => '부산',
                'country'       => '한국',
                'latitude'      => 35.1587,
                'longitude'     => 129.1603,
                'category'      => 'beach',
                'thumbnail_url' => null,
                'rating'        => 4.6,
            ],
            [
                'name'          => '광안리해수욕장',
                'description'   => '광안대교의 야경이 아름다운 부산의 명소. 젊은 층에게 인기 있는 카페와 음식점이 즐비하다.',
                'address'       => '부산광역시 수영구 광안해변로 219',
                'city'          => '부산',
                'country'       => '한국',
                'latitude'      => 35.1531,
                'longitude'     => 129.1186,
                'category'      => 'beach',
                'thumbnail_url' => null,
                'rating'        => 4.7,
            ],
            [
                'name'          => '감천문화마을',
                'description'   => '알록달록한 집들이 계단식으로 펼쳐진 부산의 마추픽추. 골목 예술과 포토존으로 인기 관광지.',
                'address'       => '부산광역시 사하구 감내2로 203',
                'city'          => '부산',
                'country'       => '한국',
                'latitude'      => 35.0975,
                'longitude'     => 129.0100,
                'category'      => 'cultural',
                'thumbnail_url' => null,
                'rating'        => 4.5,
            ],
            [
                'name'          => '자갈치시장',
                'description'   => '한국 최대의 수산물 시장. 싱싱한 해산물을 바로 구입해 식당에서 즐길 수 있는 부산의 대표 명물.',
                'address'       => '부산광역시 중구 자갈치해안로 52',
                'city'          => '부산',
                'country'       => '한국',
                'latitude'      => 35.0974,
                'longitude'     => 129.0301,
                'category'      => 'restaurant',
                'thumbnail_url' => null,
                'rating'        => 4.4,
            ],
            // 서울
            [
                'name'          => '경복궁',
                'description'   => '조선 왕조의 으뜸 궁궐. 국립고궁박물관과 국립민속박물관이 인접해 있으며 한복 대여 체험이 인기.',
                'address'       => '서울특별시 종로구 사직로 161',
                'city'          => '서울',
                'country'       => '한국',
                'latitude'      => 37.5796,
                'longitude'     => 126.9770,
                'category'      => 'cultural',
                'thumbnail_url' => null,
                'rating'        => 4.7,
            ],
            [
                'name'          => '북촌한옥마을',
                'description'   => '경복궁과 창덕궁 사이에 위치한 한옥 밀집 지역. 전통 공예 체험과 고즈넉한 골목 산책을 즐길 수 있다.',
                'address'       => '서울특별시 종로구 계동길 37',
                'city'          => '서울',
                'country'       => '한국',
                'latitude'      => 37.5828,
                'longitude'     => 126.9844,
                'category'      => 'cultural',
                'thumbnail_url' => null,
                'rating'        => 4.5,
            ],
            [
                'name'          => '남산서울타워',
                'description'   => '서울의 상징적인 랜드마크. 전망대에서 서울 전경을 한눈에 감상할 수 있으며 케이블카로 오를 수 있다.',
                'address'       => '서울특별시 용산구 남산공원길 105',
                'city'          => '서울',
                'country'       => '한국',
                'latitude'      => 37.5512,
                'longitude'     => 126.9882,
                'category'      => 'attraction',
                'thumbnail_url' => null,
                'rating'        => 4.6,
            ],
            [
                'name'          => '명동',
                'description'   => '서울 최대의 쇼핑·관광 중심지. K-뷰티 브랜드, 길거리 음식, 백화점이 밀집해 외국인 관광객에게 특히 인기.',
                'address'       => '서울특별시 중구 명동길 일대',
                'city'          => '서울',
                'country'       => '한국',
                'latitude'      => 37.5636,
                'longitude'     => 126.9826,
                'category'      => 'city',
                'thumbnail_url' => null,
                'rating'        => 4.3,
            ],
        ];

        foreach ($places as $place) {
            Place::create($place);
        }

        $this->command->info('장소 시드 데이터 ' . count($places) . '개 삽입 완료');
    }
}
